#!/bin/sh

# Set these paths appropriately

BIN=/Users/devonzuegel/Github/tree-tagger/bin
CMD=/Users/devonzuegel/Github/tree-tagger/cmd
LIB=/Users/devonzuegel/Github/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
