#!/bin/sh

# Set these paths appropriately

parentdir="$(dirname "$(pwd)")"/pa6-spanish-translation

BIN=${parentdir}/tree-tagger/bin
CMD=${parentdir}/tree-tagger/cmd
LIB=${parentdir}/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=utf8-tokenize.perl
MWL=mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish-utf8.par
MWLFILE=${LIB}/spanish-mwls-utf8

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
